monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: sentry
            excluded_http_codes: [404, 405]
        sentry:
            type: service
            id: Sentry\Monolog\Handler
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
