sentry:
    dsn: '%env(resolve:SENTRY_DSN)%'
    register_error_listener: false
    options:
        environment: '%kernel.environment%'
    monolog:
        error_handler:
            enabled: true
            level: error
