easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        JobOffer:
            class: App\Entity\JobOffer
            list:
                fields: ['id', 'title', 'company']
            form:
                fields:
                    - { type: 'group', label: 'Job Offer Details', icon: 'paperclip' }
                    - { property: 'slug', type_options: { 'disabled': true } }
                    - { property: 'title' }
                    - { property: 'description', type: text_editor }
                    - { property: 'seniorityLevel' }
                    - { property: 'minimumSalary' }
                    - { property: 'maximumSalary' }
                    - { property: 'allowRemote' }
                    - { property: 'publishedAt', type_options: { widget: 'single_text' } }
                    -   property: 'status'
                        type: 'choice'
                        type_options:
                            choices:
                                'Pending review': 'PENDING_REVIEW'
                                'Approved': 'APPROVED'
                    -   property: 'hiringType'
                        type: 'choice'
                        type_options:
                            choices:
                                'CLT': 'CLT'
                                'PJ': 'PJ'
                    - { property: 'tags' , type_options: { by_reference: false } }
                    - { property: 'company' }
